#!/usr/bin/env node
// Runs all validators and writes reports/quality-latest.md
// Gate: fails only on P0 and clearly structural P1 findings (see lib.isBlocking).
'use strict';
const { spawnSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const L = require('./lib');

const hasSite = fs.existsSync(path.join(L.ROOT, '_site'));
const tools = ['frontmatter-check', 'content-duplicate-check', 'internal-link-audit', 'seo-audit', 'sitemap-check', 'schema-check'];
if (hasSite) tools.push('rendered-site-audit');
else console.log('build-report: _site/ not found, skipping rendered-site-audit');

const results = {};
for (const t of tools) {
  const r = spawnSync(process.execPath, [path.join(__dirname, t + '.js')], { encoding: 'utf8' });
  results[t] = { status: r.status, stdout: ((r.stdout || '') + (r.stderr || '')).trim() };
  const jf = path.join(L.ROOT, 'reports', t + '.json');
  if (fs.existsSync(jf)) results[t].data = JSON.parse(fs.readFileSync(jf, 'utf8'));
}

const counts = { P0: 0, P1: 0, P2: 0, P3: 0 };
const allFindings = [];
for (const t of tools) for (const f of (results[t].data ? results[t].data.findings : [])) { allFindings.push(Object.assign({ tool: t }, f)); counts[f.severity]++; }
const blocking = allFindings.filter(L.isBlocking);

const articles = L.loadArticles();
// TOTAL PAGES: actual indexable pages (sitemap-expected set), not README or excluded files
const totalPages = L.expectedIndexableUrls(articles).size;

const data = (t, k, d) => (results[t] && results[t].data && results[t].data[k] !== undefined) ? results[t].data[k] : d;
const broken = data('internal-link-audit', 'brokenLinks', 0);
const orphans = data('internal-link-audit', 'orphans', 0);
const gaps = data('sitemap-check', 'gaps', 0);

// Precise metric mapping (no double counting)
const dupTitles = allFindings.filter(f => f.issue.startsWith('duplicate title')).length;
const dupSlugs = allFindings.filter(f => f.tool === 'frontmatter-check' && f.issue.startsWith('duplicate slug')).length;
const missingMeta = allFindings.filter(f => f.issue.startsWith('missing title') || f.issue.startsWith('missing meta description')).length;
// MISSING SCHEMA: actual missing required schema, not every schema-check finding
const missingSchema = allFindings.filter(f => f.tool === 'schema-check' && /missing|required|without/i.test(f.issue) && !/conflict|duplicate/i.test(f.issue)).length
  + allFindings.filter(f => f.tool === 'rendered-site-audit' && f.issue.includes('missing Article/BlogPosting schema')).length;
const fmErrors = allFindings.filter(f => f.tool === 'frontmatter-check' && L.isBlocking(f)).length;

let md = '# Quality Report — ' + new Date().toISOString() + '\n\n';
md += 'Generated by scripts/build-report.js' + (hasSite ? ' including rendered-site audit of _site/' : ' from source files (no _site/ build available)') + '.\n\n';
md += '## Summary\n\n';
md += '| Metric | Value |\n|---|---|\n';
md += '| TOTAL PAGES | ' + totalPages + ' (indexable) |\n';
md += '| TOTAL ARTICLES | ' + articles.length + ' |\n';
md += '| P0 | ' + counts.P0 + ' |\n| P1 | ' + counts.P1 + ' |\n| P2 | ' + counts.P2 + ' |\n| P3 | ' + counts.P3 + ' |\n';
md += '| BLOCKING FINDINGS | ' + blocking.length + ' |\n';
md += '| BROKEN LINKS | ' + broken + ' |\n| ORPHAN PAGES | ' + orphans + ' |\n';
md += '| DUPLICATE TITLES | ' + dupTitles + ' |\n| DUPLICATE SLUGS | ' + dupSlugs + ' |\n';
md += '| MISSING META | ' + missingMeta + ' |\n| MISSING SCHEMA | ' + missingSchema + ' |\n';
md += '| SITEMAP GAPS | ' + gaps + ' |\n| FRONTMATTER ERRORS | ' + fmErrors + ' |\n';
md += '\n## Findings\n\n';
const order = { P0: 0, P1: 1, P2: 2, P3: 3 };
allFindings.sort((a, b) => order[a.severity] - order[b.severity]);
if (allFindings.length === 0) md += 'No findings.\n';
for (const f of allFindings) {
  md += '- **' + f.severity + (L.isBlocking(f) ? ' (BLOCKING)**' : '**') + ' — ' + f.file + (f.url && f.url !== '-' ? ' (' + f.url + ')' : '') + ' — ' + f.issue + '\n  Fix: ' + f.fix + '\n';
}
md += '\n## Tool exit statuses\n\n';
for (const t of tools) md += '- ' + t + ': exit ' + results[t].status + '\n';
md += '\nQuality gate fails only on P0 and clearly structural P1 findings (duplicate slug, YAML failure, missing required fields, unknown topic_cluster, legal VERIFIED without primary sources, invalid dates, broken links, missing slugs, missing hubs, doubled /english/english paths, duplicate canonicals, noindex/sitemap integrity, invalid JSON-LD, broken breadcrumbs). P2/P3 never block.\n';

fs.mkdirSync(path.join(L.ROOT, 'reports'), { recursive: true });
fs.writeFileSync(path.join(L.ROOT, 'reports', 'quality-latest.md'), md);
console.log(md.split('\n').slice(0, 26).join('\n'));

if (blocking.length > 0) {
  console.error('QUALITY GATE: FAIL (blocking findings: ' + blocking.length + ')');
  for (const f of blocking) console.error('  ' + f.severity + ' ' + f.file + ' — ' + f.issue);
  process.exit(1);
}
console.log('QUALITY GATE: PASS');
