#!/usr/bin/env node
// Runs all validators and writes reports/quality-latest.md
'use strict';
const { spawnSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const L = require('./lib');

const tools = ['frontmatter-check', 'content-duplicate-check', 'internal-link-audit', 'seo-audit', 'sitemap-check', 'schema-check'];
const results = {};
for (const t of tools) {
  const r = spawnSync(process.execPath, [path.join(__dirname, t + '.js')], { encoding: 'utf8' });
  results[t] = { status: r.status, stdout: (r.stdout || '') + (r.stderr || '') };
  const jf = path.join(L.ROOT, 'reports', t + '.json');
  if (fs.existsSync(jf)) results[t].data = JSON.parse(fs.readFileSync(jf, 'utf8'));
}

const counts = { P0: 0, P1: 0, P2: 0, P3: 0 };
const allFindings = [];
for (const t of tools) for (const f of (results[t].data ? results[t].data.findings : [])) { allFindings.push(Object.assign({ tool: t }, f)); counts[f.severity]++; }

const articles = L.loadArticles();
const pages = L.loadPages().filter(p => !p.file.startsWith('_'));
const broken = (results['internal-link-audit'].data ? results['internal-link-audit'].data.brokenLinks : 0);
const orphans = (results['internal-link-audit'].data ? results['internal-link-audit'].data.orphans : 0);
const gaps = (results['sitemap-check'].data ? results['sitemap-check'].data.gaps : 0);

const by = (fn) => allFindings.filter(fn).length;
const dupTitles = by(f => f.tool === 'seo-audit' && f.issue.startsWith('duplicate title'));
const dupSlugs = by(f => f.tool === 'frontmatter-check' && f.issue.startsWith('duplicate slug'));
const missingMeta = by(f => f.issue.includes('missing meta description') || f.issue.includes('missing title'));
const missingSchema = by(f => f.tool === 'schema-check');
const fmErr = by(f => f.tool === 'frontmatter-check' && f.severity === 'P1');

let md = '# Quality Report — ' + new Date().toISOString() + '\n\n';
md += 'Generated by scripts/build-report.js from source files (no network access).\n\n';
md += '## Summary\n\n';
md += '| Metric | Value |\n|---|---|\n';
md += '| TOTAL PAGES | ' + (pages.length + 1) + ' |\n';
md += '| TOTAL ARTICLES | ' + articles.length + ' |\n';
md += '| P0 | ' + counts.P0 + ' |\n| P1 | ' + counts.P1 + ' |\n| P2 | ' + counts.P2 + ' |\n| P3 | ' + counts.P3 + ' |\n';
md += '| BROKEN LINKS | ' + broken + ' |\n| ORPHAN PAGES | ' + orphans + ' |\n';
md += '| DUPLICATE TITLES | ' + dupTitles + ' |\n| DUPLICATE SLUGS | ' + dupSlugs + ' |\n';
md += '| MISSING META | ' + missingMeta + ' |\n| MISSING SCHEMA | ' + missingSchema + ' |\n';
md += '| SITEMAP GAPS | ' + gaps + ' |\n| FRONTMATTER ERRORS | ' + fmErr + ' |\n\n';
md += '## Findings\n\n';
const order = { P0: 0, P1: 1, P2: 2, P3: 3 };
allFindings.sort((a, b) => order[a.severity] - order[b.severity]);
if (allFindings.length === 0) md += 'No findings.\n';
for (const f of allFindings) {
  md += '- **' + f.severity + '** \u2014 ' + f.file + (f.url && f.url !== '-' ? ' (' + f.url + ')' : '') + ' \u2014 ' + f.issue + '\n  Fix: ' + f.fix + '\n';
}
md += '\n## Tool exit statuses\n\n';
for (const t of tools) md += '- ' + t + ': exit ' + results[t].status + '\n';
md += '\nQuality gate fails only on P0 and structural P1 (duplicate slug, broken doubled-path, missing hub).\n';

fs.mkdirSync(path.join(L.ROOT, 'reports'), { recursive: true });
fs.writeFileSync(path.join(L.ROOT, 'reports', 'quality-latest.md'), md);
console.log(md.split('\n').slice(0, 22).join('\n'));

// Gate: fail on P0, and structural P1s
const structuralP1 = allFindings.filter(f => f.severity === 'P1' && (f.issue.includes('duplicate slug') || f.issue.includes('/english/english') || f.issue.includes('missing topic hub')));
if (counts.P0 > 0 || structuralP1.length > 0) { console.error('QUALITY GATE: FAIL (P0=' + counts.P0 + ', structural P1=' + structuralP1.length + ')'); process.exit(1); }
console.log('QUALITY GATE: PASS');
